name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.7.0

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: apt update && apt install -y wget
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: make ci
